### ISSUE TITLE
Handle large CSV issue

### ISSUE THREAD

**Issue by hushirley** [derekeder/csv-to-html-table#53]
Hi, when loading a CSV file with 30000 rows, the browser wil crash!
PLS check.

**Comment by speedlover** [comment]
Hi there, i also tried to use this on a large file, in my case it was 64000 rows by 5 columns. The problem is that over a certain size it seems to increase in processing requirements exponentially. At that size i would recommend going and grabbing a drink. It will take a lot of RAM and cause high CPU usage for the entire time and on a low end computer it may take a while, but it WILL work eventually.

**Comment by stokito** [comment]
You can try  to implement a pagination yourself.
DataTables plugin [can send an additional params](https://datatables.net/manual/server-side) `start` and `length` to server so you can return only sunset of rows. 
But this is not implemented in this project so the issue is valid.

**Comment by derekeder** [comment]
agree with @stokito - handling large files is beyond what this tool can do. As it is browser/javascript based, everything needs to be loaded all at once into the browser, which means it becomes slower and eventually not possible as files get bigger.

you'll need to use `DataTables` server-side methods to serve up slices of your data: https://datatables.net/manual/server-side
