### ISSUE TITLE
Tables without column headers in the first row

### ISSUE THREAD

**Issue by rienholt** [derekeder/csv-to-html-table#72]
Good Evening,
First off love this super handy tool.

Now to my problem. I am trying to display a csv that is generated without column header information in the first row, or any row, for that matter so the tableheader is just more data. Has anyone figured out a way to insert custom table header data?

Thanks!

**Comment by derekeder** [comment]
I suggest editing the file to add the header row if possible.

If that's not an option, you could edit the code here and input an array of values with your own custom headers: https://github.com/derekeder/csv-to-html-table/blob/master/js/csv_to_html_table.js#L27

You will also need to set the for loop index to start at 0 instead of 1 here: https://github.com/derekeder/csv-to-html-table/blob/master/js/csv_to_html_table.js#L37
